### ISSUE TITLE
Realm browser column width is shrinking when we have more than 30 columns or the width of the screen is full

### ISSUE THREAD

**Issue by bsmn99** [uPhyca/stetho-realm#10]
![screenshot 25](https://cloud.githubusercontent.com/assets/6211735/12719659/83910226-c91c-11e5-8de3-4cc1792c0da3.png)

anyone help me how to increase the column width? stetho is helpful for viewing the .realm files but still i cannot be able to view it properly..

**Comment by zaki50** [comment]
Hi @bsmn99 
If Stetho-Realm supports column filter(which hides some columns), does it help?

**Comment by bsmn99** [comment]
How to hide some columns? Anyway I need to view all the column data's..

**Comment by zaki50** [comment]
There seem to be nothing I can do. Sorry.

Please request that feature to Google Chrome.
