### ISSUE TITLE
When have so many datas, how to view the next page data?

### ISSUE THREAD

**Issue by zhonghanwen** [uPhyca/stetho-realm#13]
![image](https://cloud.githubusercontent.com/assets/12220537/14308768/d66d1892-fc0a-11e5-9108-30c14f7568b9.png)

**Comment by zaki50** [comment]
Hi @zhonghanwen 

Please use `withLimit()` to list more rows when you build `RealmInspectorModulesProvider.
There is a sample in README https://github.com/uPhyca/stetho-realm/blob/master/README.md
