### ISSUE TITLE
Realm 0.90.0 file format change affects Stetho-Realm

### ISSUE THREAD

**Issue by Zhuinden** [uPhyca/stetho-realm#17]
[Realm Types in Stetho](https://github.com/uPhyca/stetho-realm/blob/master/stetho_realm/src/main/java/com/uphyca/stetho_realm/Database.java#L45-L55)  and [Realm Types in Realm](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmFieldType.java#L34-L45) are mismatched due to change in file format in 0.90.0, because of date range expanding

**Comment by zaki50** [comment]
@Zhuinden thank you for reporting.

I'll fix this soon.

**Comment by zaki50** [comment]
I released `0.9.0` which supports new Date range and null column.

I'll close this issue. If you have further question, feel free to reopen this.
