### ISSUE TITLE
Limited View on Tables

### ISSUE THREAD

**Issue by degill** [uPhyca/stetho-realm#2]
First of all: Thanks for the plugin! Awesome for Linux users who dont have the RealmBrowser :)

This may not be an issue on your side (I dont know the implementations), but if you have a huge table saved in realm than the view in stetho which lets you browse through that table stops after 250 entries and then prints a line with column-values of "truncated". 

Is there a way to browser everything in that table?

**Comment by zaki50** [comment]
@degill sorry for my late reply.

plese use `withLimit(...)`.

```
RealmInspectorModulesProvider.builder(this)
            .withFolder(getCacheDir())
            .withEncryptionKey("encrypted.realm", key)
            .withMetaTables()
            .withDescendingOrder()
            .withLimit(1000)
            .databaseNamePattern(Pattern.compile(".+\\.realm"))
            .build()
```

`withLimit()` is available stetho-realm 0.6.0 or later.
