### ISSUE TITLE
can not show anything in Web SQL

### ISSUE THREAD

**Issue by JakeWang123** [uPhyca/stetho-realm#24]
there are some data in my realm but can't show anything in Web SQL

**Comment by tuliof** [comment]
Sometimes there is nothing under Web SQL for me too. This happened today, I reconnected the device after some minutes and the database showed up.

**Comment by zaki50** [comment]
I couldn't reproduce that...

Is there any way to reproduce this?

**Comment by davidjorgensen** [comment]
ya, mine just did the same.. i was already connected to the device, updated the components, and tried to inspect.. and nothing..

thats all i got for now - will update if I find a more valid approach to reproduce

**Comment by kyanro** [comment]
I had same problem.

reproduce this
https://github.com/kyanro/reproducestethorealmissues24

https://github.com/kyanro/reproducestethorealmissues24/commit/87cc7fac3d1ad50eb33a997022e6536858851d00#diff-74fe1e060935faba547f65ab02c45fceR21

after set realm db name, can not show in Web SQL.

**Comment by chen-TeamNails** [comment]
RealmInspectorModulesProvider.builder(this)
.databaseNamePattern(Pattern.compile(".+\.realm"))
.build()
if you define the file's name , using " .databaseNamePattern(Pattern.compile(".+\.realm"))" could identify database file's name. or --->default.realm

**Comment by lucasmafra** [comment]
facing the same problem here...

**Comment by lucasmafra** [comment]
my application class: 

 Realm.init(this);
        RealmConfiguration config = new RealmConfiguration.Builder().build();
        Realm.setDefaultConfiguration(config);

        Stetho.initialize(
                Stetho.newInitializerBuilder(this)
                        .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                        .enableWebKitInspector(RealmInspectorModulesProvider.builder(this).build())
                        .build());

My build.gradle files:

compile 'com.facebook.stetho:stetho:1.4.2'
compile 'com.uphyca:stetho_realm:2.0.1'

maven { url 'https://github.com/linchaolong/stetho-realm/raw/master/maven-repo' }

Can someone tell me what I'm missing here? I think I followed all documentation tutorial but I'm not seeing anything inside Web SQL

![image](https://cloud.githubusercontent.com/assets/10407261/26226532/fcdb1414-3c02-11e7-8d83-436e40717746.png)

**Comment by dssoft32** [comment]
same issue for me too.

**Comment by zaki50** [comment]
Do you have `.realm` extension in your database name?

**Comment by dssoft32** [comment]
Yes. now i switch to default database name.. it works fine.. for a custom name, its an issue

**Comment by zaki50** [comment]
I fixed the issue in `2.1.0`. Could you update stetho-realm to 2.1.0?

**Comment by smelfungus** [comment]
@zaki50 I was facing the same issue, it's working now, thank you.

**Comment by zaki50** [comment]
@DummyCo Happy to hear that.

**Comment by BoopathiNataraj** [comment]
@zaki50  , Thank you, i was also facing same issue i cleared by your guidance thx man
