### ISSUE TITLE
Working with latest realm and stetho

### ISSUE THREAD

**Issue by eikaramba** [uPhyca/stetho-realm#26]
I forked the project(kudos to emanuelet for adding methods for realm 1.0) and updated everything. It is working for me now! Using realm 1.1.0 and stetho 1.3.1

https://github.com/eikaramba/stetho-realm

Tipps:
- Add proguard rules
- Initialize DB after stetho

**Comment by joaocsousa** [comment]
Cheers for the proguard tip 👍

**Comment by zaki50** [comment]
I've released Stetho-Realm 2.0.0 which supports Realm Java 2.0.0.
Stetho-Realm 2.0.0 contains ProGuard configuration file and users don't need to add own configuration to their apps.

I copied the configuration from your README file. Thanks @eikaramba

**Comment by eikaramba** [comment]
That is great! Thx for the update.
