### ISSUE TITLE
I do not see my app in chrome://inspect/#devices

### ISSUE THREAD

**Issue by kamilwlf** [uPhyca/stetho-realm#29]
I do not see my app in chrome://inspect/#devices

dependencies:

> compile 'com.facebook.stetho:stetho:1.3.1'
> compile 'com.uphyca:stetho_realm:0.9.0'
> classpath 'io.realm:realm-gradle-plugin:1.0.0'

my code:

>  Stetho.initialize(
>                 Stetho.newInitializerBuilder(this)
>                         .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
>                         .enableWebKitInspector(RealmInspectorModulesProvider.builder(this).build())
>                         .build());

**Comment by kazaky** [comment]
@kamilwlf  Try this config!
https://github.com/uPhyca/stetho-realm/issues/23

**Comment by kamilwlf** [comment]
thanks, it works!
why documentation is not updated?
