### ISSUE TITLE
Realm Data Explorer - Horizontal Scroll On Chrome

### ISSUE THREAD

**Issue by anwar-pasaribu** [uPhyca/stetho-realm#36]
I do really love Stetho Realm. 

But, when my Realm fields quite a lot then the table look like below (img. 01):

![report to stetho realm](https://cloud.githubusercontent.com/assets/3276486/19303059/51a81668-9091-11e6-92d7-78ddf496f327.png)

Is there any solution for those my little problem on Windows?

**Comment by Thansoft105** [comment]
please fix this .......

**Comment by zaki50** [comment]
We can't do anything about this issue.
Could you file a feature request in Chrome repository?

Thanks.
