### ISSUE TITLE
not able to compile dependency

### ISSUE THREAD

**Issue by kjoshi07** [uPhyca/stetho-realm#39]
I have defined dependencies and tried to sync gradle, it is not failed to resolve.

> debugCompile 'com.facebook.stetho:stetho:1.4.1'

> debugCompile 'com.uphyca:stetho_realm:2.0.0'

Error:(30, 18) Failed to resolve: com.uphyca:stetho-realm:2.0.0

**Comment by MihailovJava** [comment]
@kjoshi07 Perhaps you add maven repository into buildscript{ } closure

**Comment by Neoklosch** [comment]
@MihailovJava works for me. I had the same problem and moved the maven repository to:

**./build.gradle**
```
allprojects {
    repositories {
        jcenter()
        maven { url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo' }
    }
}
```

Thanks man!
