### ISSUE TITLE
Customized Realm Database name can't preview Tables from V2.0.0

### ISSUE THREAD

**Issue by bsmn99** [uPhyca/stetho-realm#40]
@zaki50 I have already reported the same issue in Realm/java Github, due to still the issue persist, i am reporting here too for reference,

here is the link https://github.com/realm/realm-java/issues/3700,

the same issues reported by other users https://github.com/uPhyca/stetho-realm/issues/35, https://github.com/uPhyca/stetho-realm/issues/37

Please fix it, its very much needed...

**Comment by trueangle** [comment]
+

**Comment by tanayagrawal** [comment]
I am also facing the same issue as mentioned by @bsmn99 . Please fix it as soon as possible.

**Comment by mlostekk** [comment]
Same here.

**Comment by sureshjoshi** [comment]
This outstanding PR should solve this: https://github.com/uPhyca/stetho-realm/pull/38

You could also take a look at my fork to see what I did. https://github.com/sureshjoshi/stetho-realm/

**Comment by zaki50** [comment]
I've released 2.1.0 that contains the fix.
I'll close this issue.
