### ISSUE TITLE
All schema show the tables of default schema

### ISSUE THREAD

**Issue by hexi** [uPhyca/stetho-realm#42]
There are 2 custom schema in library module:
@RealmModule(library = true, classes = {Elephant.class, Lion.class, Zebra.class})
public class ZooAnimalsModule {
}

@RealmModule(library = true, classes = {Cat.class, Dog.class})
public class DomesticAnimalsModule {
}

And in my application There are some Model in the default schema:
Cow, Pig, Snake, Spider

But when i run the application,  all schema show the tables of the default schema.
![image](https://cloud.githubusercontent.com/assets/2355115/20337930/f0f8c2a6-ac0e-11e6-85da-e86c9695ef5b.png)

**Comment by hexi** [comment]
in build.gradle:
compile 'com.facebook.stetho:stetho:1.4.1'  
compile 'com.uphyca:stetho_realm:2.0.0'

in MyApplication:
Stetho.initialize(
                Stetho.newInitializerBuilder(this)
                        .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                        .enableWebKitInspector(RealmInspectorModulesProvider.builder(this).build())
                        .build());

**Comment by riyase** [comment]
still i am having the same problem

**Comment by mosesleesh** [comment]
Having the same issue also. Any solution for this?

**Comment by saulIHS** [comment]
I have this issue. Any solution?

**Comment by mosesleesh** [comment]
@saulIHS try this.

stetho-realm 2.0.1 is released.

edit build.gradle:

`repositories {
    maven { url 'https://github.com/linchaolong/stetho-realm/raw/master/maven-repo' }
}`

`dependencies {
    compile 'com.facebook.stetho:stetho:1.4.2'
    compile 'com.uphyca:stetho_realm:2.0.1'
}`

**Comment by saulIHS** [comment]
@bryanleesh thanks, it works!
