### ISSUE TITLE
Cant sync gradle,Error:Could not HEAD to the Url,Received status code 503 from server: first byte timeout 

### ISSUE THREAD

**Issue by kenchoong** [uPhyca/stetho-realm#50]
I want to grab stetho-realm via Gradle in Android Studio.
Here is my Gradle code

```
allprojects {
    repositories {
        maven {
            url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'
        }
        jcenter()
    }
}
```
```
dependencies {
    compile 'com.facebook.stetho:stetho:1.4.1'
    compile 'com.uphyca:stetho_realm:2.0.0'
   //here along with my other dependecies
}
```

But when I sync the Gradle it show me this error 
![git](https://cloud.githubusercontent.com/assets/8010129/23758937/9f11971e-052e-11e7-9383-f297db87510c.png)

I even tried to adding maven and the url in my repositories,it show me this error
![git](https://cloud.githubusercontent.com/assets/8010129/23759254/88288192-052f-11e7-949e-30f816147886.png)

But I test just only stetho,it sync successfully.
` compile 'com.facebook.stetho:stetho:1.4.1'`

I havent do anything else,but can I know how to solve this??

**Comment by masbarbosa** [comment]
facing the same issue

**Comment by kenchoong** [comment]
@marcodebarbosa ,You solved this??

**Comment by masbarbosa** [comment]
No, I have not.

**Comment by Komalnegi** [comment]
same issue 
can anyone help ?

**Comment by Komalnegi** [comment]
Issue resolved
change the gradle as follows:

```groovy
allprojects {
    repositories {
        jcenter()
    }

    repositories {
        maven {
            url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'
        }
    }
}
```

**Comment by kenchoong** [comment]
@Komalnegi  bro can u post gradle code in code format?cause is quite hard to see..pleaseee
