### ISSUE TITLE
use this plugin, i only see database's name,but i can't see datebase field.

### ISSUE THREAD

**Issue by DonChengCheng** [uPhyca/stetho-realm#51]

**Comment by mikecoppola16** [comment]
Me too!

**Comment by wickedev** [comment]
remove name in your RealmConfiguration. then would be work!

**Comment by rushank** [comment]
Same issue

**Comment by witbybit** [comment]
@WickeDev Thanks! That worked for me.

I am wondering if there's any disadvantage to not naming the database. Is it possible for there to be any clash with another app?

**Comment by iamareebjamal** [comment]
@nikhilag No, your db resides in your app's private storage space

**Comment by cireficc** [comment]
@nikhilag The advantage is if you need multiple databases. You can name them differently and access them separately. However, this stetho-realm bridge does not currently handle anything but the default name, which kind of sucks for development. There are open pull requests, like #38 and #46  to solve this problem, just waiting for a merge and release.

**Comment by zaki50** [comment]
I've released 2.1.0 that contains the fix.
I'll close this issue.
