### ISSUE TITLE
don't show the newly added data.

### ISSUE THREAD

**Issue by hjmJhon** [uPhyca/stetho-realm#53]
I created a database, and in the database which added the write data, are displayed. But when I add the data again, it does not show me the newly added data.

**Comment by zaki50** [comment]
You can see the new data by clicking other table and then getting back to the target table.
Or you can use reload button at the bottom of the window.

<img width="118" alt="2017-07-20 2 25 14" src="https://user-images.githubusercontent.com/406660/28380552-b32c268e-6cf2-11e7-992a-81608563575d.png">

**Comment by zaki50** [comment]
I'm closing the issue.
Please feel free to reopen it if you have further questions.
