### ISSUE TITLE
Unable to instantiate application app.DebugApplication: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Drjacky** [uPhyca/stetho-realm#70]
I've used this tutorial: http://littlerobots.nl/blog/stetho-for-android-debug-builds-only/ to use Stetho in debug build only.
I have 2 custom classes which extended `Application`:
```javascript
public class SecondCustomApplication extends FirstCustomApplication {
```
And
```javascript
public class FirstCustomApplication extends MultiDexApplication {
```

Now the Debug class:
```javascript
public class DebugApplication extends SecondCustomApplication {
    @Override
    public void onCreate() {
        super.onCreate();
        Stetho.initialize(
                Stetho.newInitializerBuilder(this)
                        .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                        .enableWebKitInspector(Stetho.defaultInspectorModulesProvider(this))
                        .build());
    }
}
```
And in *main* AndroidManifest.xml:
```javascript
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.package.name">

<application
        android:name=".SecondCustomApplication"
        android:allowBackup="true"
        android:fullBackupContent="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:replace="icon,label,name">
```
And in *debug* AndroidManifest.xml:
```javascript
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.package.name">

    <application
        android:name="DebugApplication"
        tools:replace="name" />

</manifest>

```

But when I run the App, I get this error:

> com.package.name E/AndroidRuntime: FATAL EXCEPTION: main
	  Process: com.package.name, PID: 14078
	  java.lang.RuntimeException: Unable to instantiate application com.package.name.DebugApplication: java.lang.ClassNotFoundException: Didn't find class "com.package.name.DebugApplication" on path: DexPathList[[zip file "/data/app/com.package.name-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.package.name-1, /vendor/lib, /system/lib]]
		  at android.app.LoadedApk.makeApplication(LoadedApk.java:516)
		  ...
	   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.package.name.DebugApplication" on path: DexPathList[[zip file "/data/app/com.package.name-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.package.name-1, /vendor/lib, /system/lib]]
		  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		  at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
		  at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
		  at android.app.Instrumentation.newApplication(Instrumentation.java:975)
		  at android.app.LoadedApk.makeApplication(LoadedApk.java:511)

**Comment by ghost** [comment]
I think this is because your class "DebugApplication" isn't on the _main_ directory and in your debug Manifest you should use ` android:name=".DebugApplication"`

The only thing wich you need in your _debug_ directory is your debug Manifest.

**Comment by kostyabakay** [comment]
I have the same problem.

**Comment by Drjacky** [comment]
- Add
`implementation 'com.facebook.stetho:stetho-okhttp3:1.5.0'`
`implementation 'com.facebook.stetho:stetho:1.5.0'`
to your App build.gradle file.
- Call below method on your `CustomApplication`'s `onCreate` method:
```javascript
private void initStetho() {
        if (BuildConfig.DEBUG) {
            Stetho.initialize(
                    Stetho.newInitializerBuilder(this)
                            .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                            .enableWebKitInspector(Stetho.defaultInspectorModulesProvider(this))
                            .build()
            );
        }
    }
```
- Add this `builder.addNetworkInterceptor(new StethoInterceptor());` to the `OkHttpClient.Builder` instance.
