### ISSUE TITLE
stetho realm not working 

### ISSUE THREAD

**Issue by chonamdoo** [uPhyca/stetho-realm#8]
i use realm-0.84.1

Stetho.initialize(
                Stetho.newInitializerBuilder(this)
                        .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                        .enableWebKitInspector(RealmInspectorModulesProvider.builder(this).build())
                        .build());

 D/ChromeDevtoolsServer: onOpen
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: Page.canEmulate
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: Console.setTracingBasedTimeline
 I/ResponseBodyFileManager: Cleaned up temporary network files.
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: Debugger.setAsyncCallStackDepth
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: Debugger.skipStackFrames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: Runtime.enable
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: Worker.enable
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: Timeline.enable
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.enable
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: Page.getNavigationHistory
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: Worker.setAutoconnectToWorkers
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: Page.getNavigationHistory
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: ApplicationCache.enable
 D/ChromeDevtoolsServer: Method not implemented: Not implemented: ApplicationCache.getFramesWithManifests

**Comment by zaki50** [comment]
@chonamdoo sorry for super late reply.

What version of Stetho are you using?

**Comment by chonamdoo** [comment]
@zaki50 
i use stetho 1.2.0
    compile 'com.facebook.stetho:stetho:1.2.0'
    compile 'com.facebook.stetho:stetho-okhttp:1.2.0'

**Comment by danielgomezrico** [comment]
Not working, tried `0.8.0` and stetho `1.2.0` and realm `0.87.2`

**Comment by zaki50** [comment]
I got the same log but it seems to be working.

https://github.com/zaki50/realm_file_viewer_by_stetho is a sample application which uses `stetho-realm 0.8.0` and `stetho 1.2.0` and realm `0.87.2`

Can you try this?

![2016-01-16 2 20 46](https://cloud.githubusercontent.com/assets/406660/12359838/c7a6ed04-bbf7-11e5-8970-461366b918a3.png)

**Comment by zaki50** [comment]
Closing due to no response.
